### Loading an image - "noImage"

POST http://localhost:8080/media/multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="file"; filename="package1.png"
Content-Type: image/png

< noImage.png
--WebBoundary--

> {%
client.global.set('image', response.body.name);
%}

###  Loading an images
POST http://localhost:8080/media/multi-multipart
Content-Type: multipart/form-data; boundary=WebBoundary

--WebBoundary
Content-Disposition: form-data; name="files"; filename="package1.png"
Content-Type: image/png

< package1.png
--WebBoundary
Content-Disposition: form-data; name="files"; filename="package2.jpg"
Content-Type: image/jpeg

< package2.jpg
--WebBoundary--

### Getting a list of offices in Kazan

GET http://localhost:8080/offices/getAllInCity?city=Kazan

###  Getting a list of offices in Moscow

GET http://localhost:8080/offices/getAllInCity?city=Moscow

###  Getting a list of offices in St. Petesburg

GET http://localhost:8080/offices/getAllInCity?city=St. Petersburg

###  Obtaining complete information about the office

GET http://localhost:8080/offices/getById?id=4

### Getting exception

GET http://localhost:8080/offices/getById?id=999

### "Delete" office by id=

POST http://localhost:8080/offices/removeById?id=4

### "Open" office by id=

POST http://localhost:8080/offices/restoreById?id=4

### Create office

POST http://localhost:8080/offices/save
Content-Type: application/json

{
  "id": 0,
  "name": "KZN04",
  "city": "Kazan",
  "address": "ул. Вишневского, 10",
  "undergrounds": [
    "Суконная слобода"
  ],
  "workingHours": [
    "Пн-Пт 10:00-20:00",
    "Сб-Вс 10:00-18:00"
  ],
  "restrictionWeight": "Вес: от 0 до 35 кг",
  "description": "Ближайшие остановки: Калинина, Вишневского.100 метров от остановки Калинина по направлению в сторону улицы Достоевского, вход через магазин Пятерочка",
  "paymentMethods": [
    "Наличные",
    "Банковские карты",
    "Наложенный платеж"
  ],
  "requisitePhone": "+7(843)XXX-XX-XX",
  "requisiteEmail": "transporter@example.ru"
}

### Update office

POST http://localhost:8080/offices/save
Content-Type: application/json

{
  "id": 1,
  "name": "KZN01",
  "city": "Kazan",
  "address": "ул. тракт Сибирский, 34А",
  "undergrounds": [
    "Проспект победы"
  ],
  "workingHours": [
    "Пн-Пт 10:00-20:00",
    "Сб 10:00-18:00",
    "Вс Выходной"
  ],
  "restrictionWeight": "Вес: от 0 до 50 кг",
  "description": "Остановка Академика Арбузова,рядом многопрофильная клиника MEDEL,идти в сторону остановки Халитова",
  "paymentMethods": [
    "Наличные",
    "Банковские карты",
    "Наложенный платеж"
  ],
  "requisitePhone": "+7(843)XXX-XX-XX",
  "requisiteEmail": "transporter@example.ru"
}

### Getting a list of tariffs

GET http://localhost:8080/tariffs/getAll

### Register order

POST http://localhost:8080/orders/register
Content-Type: application/json

{
  "tariffId": 1,
  "routeId": 1,
  "images": [
    "{{image}}"
  ]
}

### Register order KZN-MOW

POST http://localhost:8080/orders/register
Content-Type: application/json

{
  "tariffId": 1,
  "routeId": 1,
  "images": []
}

### Register order KZN-St. Peterburg

POST http://localhost:8080/orders/register
Content-Type: application/json

{
  "tariffId": 2,
  "routeId": 3,
  "images": []
}
